Django - lecture 3 cs50w/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>/", views.greet, name="greet"),
    path("diogo/", views.diogo, name="diogo")
]

Django - lecture 3 cs50w/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tasks/', include("tasks.urls")),
    path('newyear/', include("newyear.urls"))
]

Django - lecture 3 cs50w/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

Django - lecture 3 cs50w/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

Django - lecture 3 cs50w/hello/models.py
from django.db import models

# Create your models here.

Django - lecture 3 cs50w/newyear/models.py
from django.db import models

# Create your models here.

Django - lecture 3 cs50w/tasks/models.py
from django.db import models

# Create your models here.

Django - lecture 3 cs50w/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def diogo(request):
    return HttpResponse("Hello, Diogo!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

Django - lecture 3 cs50w/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

Django - lecture 3 cs50w/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts  import render
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

Django - lecture 3 cs50w/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello!</title>
</head>

<body>
    <h1>Hello, {{ name }}!</h1>
</body>

</html>

Django - lecture 3 cs50w/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello!</title>
</head>

<body>
    <h1>Hello!</h1>
</body>

</html>

Django - lecture 3 cs50w/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it New Year's?</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>

<body>
    {% if newyear %}
    <h1>YES!</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}
</body>

</html>

Django - lecture 3 cs50w/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %} {% block body %}
<h1>Add Task</h1>
<form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %} {{ form }}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">Tasks list</a> {% endblock %}

Django - lecture 3 cs50w/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %} {% block body %}
<ul>
    <h1>Tasks</h1>
    {% for task in tasks %}
    <li>{{ task }}</li>
    {% empty %}
    <li>No tasks.</li>
    {% endfor %}
</ul>
<a href="{% url 'tasks:add' %}">Add a new task</a> {% endblock %}

Django - lecture 3 cs50w/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% block body %} {% endblock %}
</body>

</html>